// GENERATED from spec 004 content decisions (CDC/OMS/AAP).
// Do not edit by hand. Pure Dart, no Flutter imports.
import 'development_area.dart';
import 'milestone_guide.dart';
import 'milestone_month.dart';

const String medicalDisclaimer =
    'Esta información es orientativa y no sustituye el consejo de un profesional de salud.';

const List<MonthContent> _allContent = [
  MonthContent(
    month: MilestoneMonth.month1,
    label: 'Nacimiento a 1 mes',
    areas: [
      AreaMilestones(
        area: DevelopmentArea.grossMotor,
        label: 'Motricidad gruesa',
        newMilestones: ['Levanta la cabeza brevemente al estar boca abajo', 'Mueve brazos y piernas'],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.fineMotor,
        label: 'Motricidad fina',
        newMilestones: ['Aprieta el puño y abre las manos'],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.language,
        label: 'Lenguaje',
        newMilestones: ['Llora para comunicarse', 'Reacciona a los sonidos'],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.socialEmotional,
        label: 'Social/afectivo',
        newMilestones: ['Mira tu cara y te observa', 'Se calma al estar cerca de ti'],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.cognitive,
        label: 'Cognitivo',
        newMilestones: ['Observa caras y objetos', 'Sigue un objeto con la mirada'],
        alarmSigns: [],
      ),
    ],
    medicalDisclaimer: medicalDisclaimer,
  ),
  MonthContent(
    month: MilestoneMonth.month2,
    label: '1 a 2 meses',
    areas: [
      AreaMilestones(
        area: DevelopmentArea.grossMotor,
        label: 'Motricidad gruesa',
        newMilestones: ['Levanta la cabeza y parte del pecho boca abajo'],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.fineMotor,
        label: 'Motricidad fina',
        newMilestones: ['Sigue un objeto con la mirada', 'Abre y cierra las manos'],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.language,
        label: 'Lenguaje',
        newMilestones: ['Hace sonidos guturales', 'Se vuelve ante un sonido'],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.socialEmotional,
        label: 'Social/afectivo',
        newMilestones: ['Sonríe por primera vez a propósito', 'Te sigue con la mirada'],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.cognitive,
        label: 'Cognitivo',
        newMilestones: ['Presta atención a las caras', 'Explora con la vista'],
        alarmSigns: [],
      ),
    ],
    medicalDisclaimer: medicalDisclaimer,
  ),
  MonthContent(
    month: MilestoneMonth.month3,
    label: '2 a 3 meses',
    areas: [
      AreaMilestones(
        area: DevelopmentArea.grossMotor,
        label: 'Motricidad gruesa',
        newMilestones: ['Sostiene la cabeza sin apoyo'],
        alarmSigns: ['No sostiene la cabeza'],
      ),
      AreaMilestones(
        area: DevelopmentArea.fineMotor,
        label: 'Motricidad fina',
        newMilestones: ['Juega con sus manos', 'Agarra un sonajero al ofrecérselo'],
        alarmSigns: ['No agarra objetos'],
      ),
      AreaMilestones(
        area: DevelopmentArea.language,
        label: 'Lenguaje',
        newMilestones: ['Sonríe al oír tu voz', 'Emite sonidos de arrullo'],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.socialEmotional,
        label: 'Social/afectivo',
        newMilestones: ['Sonríe ante tu cara', 'Empieza a socializar con sonrisas'],
        alarmSigns: ['No sonríe a las personas'],
      ),
      AreaMilestones(
        area: DevelopmentArea.cognitive,
        label: 'Cognitivo',
        newMilestones: ['Reconoce tu cara', 'Sigue objetos en movimiento'],
        alarmSigns: [],
      ),
    ],
    medicalDisclaimer: medicalDisclaimer,
  ),
  MonthContent(
    month: MilestoneMonth.month4,
    label: '3 a 4 meses',
    areas: [
      AreaMilestones(
        area: DevelopmentArea.grossMotor,
        label: 'Motricidad gruesa',
        newMilestones: ['Se apoya en los antebrazos boca abajo'],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.fineMotor,
        label: 'Motricidad fina',
        newMilestones: ['Lleva las manos a la boca', 'Agarra objetos de forma refleja'],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.language,
        label: 'Lenguaje',
        newMilestones: ['Balbucea y hace sonidos variados'],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.socialEmotional,
        label: 'Social/afectivo',
        newMilestones: ['Responde con sonrisas y sonidos', 'Disfruta jugando contigo'],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.cognitive,
        label: 'Cognitivo',
        newMilestones: ['Explora con las manos y la boca', 'Reacciona ante su reflejo'],
        alarmSigns: [],
      ),
    ],
    medicalDisclaimer: medicalDisclaimer,
  ),
  MonthContent(
    month: MilestoneMonth.month5,
    label: '4 a 5 meses',
    areas: [
      AreaMilestones(
        area: DevelopmentArea.grossMotor,
        label: 'Motricidad gruesa',
        newMilestones: ['Se voltea de la barriga a la espalda'],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.fineMotor,
        label: 'Motricidad fina',
        newMilestones: ['Alcanza y agarra un juguete'],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.language,
        label: 'Lenguaje',
        newMilestones: ['Se ríe en voz alta', 'Balbucea con tono'],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.socialEmotional,
        label: 'Social/afectivo',
        newMilestones: ['Se ríe a carcajadas', 'Distingue a sus cuidadores'],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.cognitive,
        label: 'Cognitivo',
        newMilestones: ['Busca un objeto que se le cae', 'Explora con la mirada'],
        alarmSigns: [],
      ),
    ],
    medicalDisclaimer: medicalDisclaimer,
  ),
  MonthContent(
    month: MilestoneMonth.month6,
    label: '5 a 6 meses',
    areas: [
      AreaMilestones(
        area: DevelopmentArea.grossMotor,
        label: 'Motricidad gruesa',
        newMilestones: ['Se sienta con apoyo', 'Se voltea en ambos sentidos'],
        alarmSigns: ['No sostiene la cabeza', 'No se voltea'],
      ),
      AreaMilestones(
        area: DevelopmentArea.fineMotor,
        label: 'Motricidad fina',
        newMilestones: ['Pasa objetos de una mano a otra'],
        alarmSigns: ['No lleva objetos a la boca', 'No agarra objetos'],
      ),
      AreaMilestones(
        area: DevelopmentArea.language,
        label: 'Lenguaje',
        newMilestones: ['Balbucea: hace sonidos sin sentido, primer paso hacia el habla'],
        alarmSigns: ['No responde a los sonidos', 'No balbucea'],
      ),
      AreaMilestones(
        area: DevelopmentArea.socialEmotional,
        label: 'Social/afectivo',
        newMilestones: ['Reconoce caras conocidas', 'Sonríe ante su reflejo'],
        alarmSigns: ['No muestra afecto ni interés por las personas'],
      ),
      AreaMilestones(
        area: DevelopmentArea.cognitive,
        label: 'Cognitivo',
        newMilestones: ['Explora objetos con la boca y las manos'],
        alarmSigns: ['No explora objetos'],
      ),
    ],
    medicalDisclaimer: medicalDisclaimer,
  ),
  MonthContent(
    month: MilestoneMonth.month7,
    label: '6 a 7 meses',
    areas: [
      AreaMilestones(
        area: DevelopmentArea.grossMotor,
        label: 'Motricidad gruesa',
        newMilestones: ['Se sienta solo unos segundos'],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.fineMotor,
        label: 'Motricidad fina',
        newMilestones: ['Agarra objetos con la palma', 'Golpea dos objetos entre sí'],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.language,
        label: 'Lenguaje',
        newMilestones: ['Balbucea series de sonidos', 'Reacciona a su nombre'],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.socialEmotional,
        label: 'Social/afectivo',
        newMilestones: ['Muestra preferencia por personas conocidas', 'Responde a tu estado de ánimo'],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.cognitive,
        label: 'Cognitivo',
        newMilestones: ['Busca y encuentra objetos escondidos a medias'],
        alarmSigns: [],
      ),
    ],
    medicalDisclaimer: medicalDisclaimer,
  ),
  MonthContent(
    month: MilestoneMonth.month8,
    label: '7 a 8 meses',
    areas: [
      AreaMilestones(
        area: DevelopmentArea.grossMotor,
        label: 'Motricidad gruesa',
        newMilestones: ['Se sienta sin apoyo'],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.fineMotor,
        label: 'Motricidad fina',
        newMilestones: ['Arrastra objetos y los suelta a propósito'],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.language,
        label: 'Lenguaje',
        newMilestones: ['Balbucea con entonación', 'Entiende el "no"'],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.socialEmotional,
        label: 'Social/afectivo',
        newMilestones: ['Disfruta juegos de esconderse y aparecer', 'Imita gestos simples'],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.cognitive,
        label: 'Cognitivo',
        newMilestones: ['Explora con los sentidos', 'Mueve un objeto para conseguir otro'],
        alarmSigns: [],
      ),
    ],
    medicalDisclaimer: medicalDisclaimer,
  ),
  MonthContent(
    month: MilestoneMonth.month9,
    label: '8 a 9 meses',
    areas: [
      AreaMilestones(
        area: DevelopmentArea.grossMotor,
        label: 'Motricidad gruesa',
        newMilestones: ['Se pone de pie con apoyo'],
        alarmSigns: ['No se sienta con apoyo'],
      ),
      AreaMilestones(
        area: DevelopmentArea.fineMotor,
        label: 'Motricidad fina',
        newMilestones: ['Usa la pinza con el dedo índice y pulgar'],
        alarmSigns: ['No pasa objetos de una mano a otra'],
      ),
      AreaMilestones(
        area: DevelopmentArea.language,
        label: 'Lenguaje',
        newMilestones: ['Dice "mamá" y "papá" sin sentido preciso', 'Señala para pedir'],
        alarmSigns: ['No balbucea', 'No responde a su nombre'],
      ),
      AreaMilestones(
        area: DevelopmentArea.socialEmotional,
        label: 'Social/afectivo',
        newMilestones: ['Muestra miedo a personas desconocidas (ansiedad ante extraños)'],
        alarmSigns: ['No responde a las personas', 'No sonríe ni se ríe'],
      ),
      AreaMilestones(
        area: DevelopmentArea.cognitive,
        label: 'Cognitivo',
        newMilestones: ['Busca objetos escondidos', 'Imita gestos y sonidos'],
        alarmSigns: ['No busca cosas que ve', 'No imita gestos'],
      ),
    ],
    medicalDisclaimer: medicalDisclaimer,
  ),
  MonthContent(
    month: MilestoneMonth.month10,
    label: '9 a 10 meses',
    areas: [
      AreaMilestones(
        area: DevelopmentArea.grossMotor,
        label: 'Motricidad gruesa',
        newMilestones: ['Gatea', 'Se pone de pie agarrándose a muebles'],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.fineMotor,
        label: 'Motricidad fina',
        newMilestones: ['Señala con el índice'],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.language,
        label: 'Lenguaje',
        newMilestones: ['Hace gestos como adiós', 'Balbucea conversaciones'],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.socialEmotional,
        label: 'Social/afectivo',
        newMilestones: ['Levanta los brazos para que lo alcen', 'Interactúa con gestos'],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.cognitive,
        label: 'Cognitivo',
        newMilestones: ['Encuentra objetos escondidos por completo', 'Junta y suelta objetos'],
        alarmSigns: [],
      ),
    ],
    medicalDisclaimer: medicalDisclaimer,
  ),
  MonthContent(
    month: MilestoneMonth.month11,
    label: '10 a 11 meses',
    areas: [
      AreaMilestones(
        area: DevelopmentArea.grossMotor,
        label: 'Motricidad gruesa',
        newMilestones: ['Camina sostenido de las manos'],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.fineMotor,
        label: 'Motricidad fina',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.language,
        label: 'Lenguaje',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.socialEmotional,
        label: 'Social/afectivo',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.cognitive,
        label: 'Cognitivo',
        newMilestones: [],
        alarmSigns: [],
      ),
    ],
    medicalDisclaimer: medicalDisclaimer,
  ),
  MonthContent(
    month: MilestoneMonth.month12,
    label: '11 a 12 meses',
    areas: [
      AreaMilestones(
        area: DevelopmentArea.grossMotor,
        label: 'Motricidad gruesa',
        newMilestones: ['Da sus primeros pasos solo'],
        alarmSigns: ['No se sienta solo', 'No se pone de pie con apoyo'],
      ),
      AreaMilestones(
        area: DevelopmentArea.fineMotor,
        label: 'Motricidad fina',
        newMilestones: ['Pasa las páginas de un libro de cartón'],
        alarmSigns: ['No agarra objetos con la pinza'],
      ),
      AreaMilestones(
        area: DevelopmentArea.language,
        label: 'Lenguaje',
        newMilestones: ['Dice una o dos palabras con sentido', 'Responde a preguntas sencillas'],
        alarmSigns: ['No dice ninguna palabra'],
      ),
      AreaMilestones(
        area: DevelopmentArea.socialEmotional,
        label: 'Social/afectivo',
        newMilestones: ['Dice adiós con la mano', 'Llora o se angustia si te alejas (separación ansiosa)'],
        alarmSigns: ['No muestra interés por personas conocidas'],
      ),
      AreaMilestones(
        area: DevelopmentArea.cognitive,
        label: 'Cognitivo',
        newMilestones: ['Explora por imitación', 'Entiende el uso de objetos sencillos'],
        alarmSigns: ['No busca objetos escondidos'],
      ),
    ],
    medicalDisclaimer: medicalDisclaimer,
  ),
  MonthContent(
    month: MilestoneMonth.month13,
    label: '12 a 13 meses',
    areas: [
      AreaMilestones(
        area: DevelopmentArea.grossMotor,
        label: 'Motricidad gruesa',
        newMilestones: ['Camina solo'],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.fineMotor,
        label: 'Motricidad fina',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.language,
        label: 'Lenguaje',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.socialEmotional,
        label: 'Social/afectivo',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.cognitive,
        label: 'Cognitivo',
        newMilestones: [],
        alarmSigns: [],
      ),
    ],
    medicalDisclaimer: medicalDisclaimer,
  ),
  MonthContent(
    month: MilestoneMonth.month14,
    label: '13 a 14 meses',
    areas: [
      AreaMilestones(
        area: DevelopmentArea.grossMotor,
        label: 'Motricidad gruesa',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.fineMotor,
        label: 'Motricidad fina',
        newMilestones: ['Hace torres con dos bloques'],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.language,
        label: 'Lenguaje',
        newMilestones: ['Dice tres o más palabras', 'Señala partes del cuerpo'],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.socialEmotional,
        label: 'Social/afectivo',
        newMilestones: ['Muestra afecto con abrazos y besos', 'Reconoce su nombre'],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.cognitive,
        label: 'Cognitivo',
        newMilestones: ['Busca objetos escondidos de verdad', 'Señala objetos por su nombre'],
        alarmSigns: [],
      ),
    ],
    medicalDisclaimer: medicalDisclaimer,
  ),
  MonthContent(
    month: MilestoneMonth.month15,
    label: '14 a 15 meses',
    areas: [
      AreaMilestones(
        area: DevelopmentArea.grossMotor,
        label: 'Motricidad gruesa',
        newMilestones: ['Se agacha y se levanta', 'Sube escaleras gateando'],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.fineMotor,
        label: 'Motricidad fina',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.language,
        label: 'Lenguaje',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.socialEmotional,
        label: 'Social/afectivo',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.cognitive,
        label: 'Cognitivo',
        newMilestones: [],
        alarmSigns: [],
      ),
    ],
    medicalDisclaimer: medicalDisclaimer,
  ),
  MonthContent(
    month: MilestoneMonth.month16,
    label: '15 a 16 meses',
    areas: [
      AreaMilestones(
        area: DevelopmentArea.grossMotor,
        label: 'Motricidad gruesa',
        newMilestones: ['Se sube y baja solo de un peldaño'],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.fineMotor,
        label: 'Motricidad fina',
        newMilestones: ['Quita la tapa de una caja'],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.language,
        label: 'Lenguaje',
        newMilestones: ['Entiende frases y órdenes sencillas'],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.socialEmotional,
        label: 'Social/afectivo',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.cognitive,
        label: 'Cognitivo',
        newMilestones: [],
        alarmSigns: [],
      ),
    ],
    medicalDisclaimer: medicalDisclaimer,
  ),
  MonthContent(
    month: MilestoneMonth.month17,
    label: '16 a 17 meses',
    areas: [
      AreaMilestones(
        area: DevelopmentArea.grossMotor,
        label: 'Motricidad gruesa',
        newMilestones: ['Camina bien y sube un escalón con apoyo'],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.fineMotor,
        label: 'Motricidad fina',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.language,
        label: 'Lenguaje',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.socialEmotional,
        label: 'Social/afectivo',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.cognitive,
        label: 'Cognitivo',
        newMilestones: [],
        alarmSigns: [],
      ),
    ],
    medicalDisclaimer: medicalDisclaimer,
  ),
  MonthContent(
    month: MilestoneMonth.month18,
    label: '17 a 18 meses',
    areas: [
      AreaMilestones(
        area: DevelopmentArea.grossMotor,
        label: 'Motricidad gruesa',
        newMilestones: ['Corre', 'Sube escaleras con ayuda'],
        alarmSigns: ['No puede sostenerse de pie'],
      ),
      AreaMilestones(
        area: DevelopmentArea.fineMotor,
        label: 'Motricidad fina',
        newMilestones: ['Garabatea por sí solo', 'Hace torres con tres o cuatro bloques'],
        alarmSigns: ['No usa ambas manos'],
      ),
      AreaMilestones(
        area: DevelopmentArea.language,
        label: 'Lenguaje',
        newMilestones: ['Dice entre 6 y 20 palabras', 'Nombra objetos conocidos', 'Empieza el juego funcional (usar un objeto para su propósito, por ejemplo beber de un vaso)'],
        alarmSigns: ['No dice ninguna palabra con sentido'],
      ),
      AreaMilestones(
        area: DevelopmentArea.socialEmotional,
        label: 'Social/afectivo',
        newMilestones: ['Imita a otros en el juego', 'Juega junto a otros niños (juego paralelo)'],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.cognitive,
        label: 'Cognitivo',
        newMilestones: ['Reconoce nombres de objetos y personas', 'Empieza el juego funcional'],
        alarmSigns: [],
      ),
    ],
    medicalDisclaimer: medicalDisclaimer,
  ),
  MonthContent(
    month: MilestoneMonth.month19,
    label: '18 a 19 meses',
    areas: [
      AreaMilestones(
        area: DevelopmentArea.grossMotor,
        label: 'Motricidad gruesa',
        newMilestones: ['Se agacha y se levanta sin ayuda'],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.fineMotor,
        label: 'Motricidad fina',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.language,
        label: 'Lenguaje',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.socialEmotional,
        label: 'Social/afectivo',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.cognitive,
        label: 'Cognitivo',
        newMilestones: [],
        alarmSigns: [],
      ),
    ],
    medicalDisclaimer: medicalDisclaimer,
  ),
  MonthContent(
    month: MilestoneMonth.month20,
    label: '19 a 20 meses',
    areas: [
      AreaMilestones(
        area: DevelopmentArea.grossMotor,
        label: 'Motricidad gruesa',
        newMilestones: ['Se sube y baja solo de la silla'],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.fineMotor,
        label: 'Motricidad fina',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.language,
        label: 'Lenguaje',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.socialEmotional,
        label: 'Social/afectivo',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.cognitive,
        label: 'Cognitivo',
        newMilestones: [],
        alarmSigns: [],
      ),
    ],
    medicalDisclaimer: medicalDisclaimer,
  ),
  MonthContent(
    month: MilestoneMonth.month21,
    label: '20 a 21 meses',
    areas: [
      AreaMilestones(
        area: DevelopmentArea.grossMotor,
        label: 'Motricidad gruesa',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.fineMotor,
        label: 'Motricidad fina',
        newMilestones: ['Pasa las páginas de un libro de verdad'],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.language,
        label: 'Lenguaje',
        newMilestones: ['Dice frases de dos palabras', 'Sigue órdenes sencillas'],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.socialEmotional,
        label: 'Social/afectivo',
        newMilestones: ['Expresa emociones y gustos', 'Demuestra afecto a otros niños'],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.cognitive,
        label: 'Cognitivo',
        newMilestones: ['Imita tareas de casa', 'Comprende palabras de uso'],
        alarmSigns: [],
      ),
    ],
    medicalDisclaimer: medicalDisclaimer,
  ),
  MonthContent(
    month: MilestoneMonth.month22,
    label: '21 a 22 meses',
    areas: [
      AreaMilestones(
        area: DevelopmentArea.grossMotor,
        label: 'Motricidad gruesa',
        newMilestones: ['Salta con los dos pies'],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.fineMotor,
        label: 'Motricidad fina',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.language,
        label: 'Lenguaje',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.socialEmotional,
        label: 'Social/afectivo',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.cognitive,
        label: 'Cognitivo',
        newMilestones: [],
        alarmSigns: [],
      ),
    ],
    medicalDisclaimer: medicalDisclaimer,
  ),
  MonthContent(
    month: MilestoneMonth.month23,
    label: '22 a 23 meses',
    areas: [
      AreaMilestones(
        area: DevelopmentArea.grossMotor,
        label: 'Motricidad gruesa',
        newMilestones: ['Se mantiene en cuclillas con más control'],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.fineMotor,
        label: 'Motricidad fina',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.language,
        label: 'Lenguaje',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.socialEmotional,
        label: 'Social/afectivo',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.cognitive,
        label: 'Cognitivo',
        newMilestones: [],
        alarmSigns: [],
      ),
    ],
    medicalDisclaimer: medicalDisclaimer,
  ),
  MonthContent(
    month: MilestoneMonth.month24,
    label: '23 a 24 meses',
    areas: [
      AreaMilestones(
        area: DevelopmentArea.grossMotor,
        label: 'Motricidad gruesa',
        newMilestones: ['Sube y baja escaleras solo'],
        alarmSigns: ['No camina'],
      ),
      AreaMilestones(
        area: DevelopmentArea.fineMotor,
        label: 'Motricidad fina',
        newMilestones: ['Hace torres con seis bloques', 'Vuelve las páginas de una en una'],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.language,
        label: 'Lenguaje',
        newMilestones: ['Dice entre 50 y 100 palabras', 'Hace frases de dos a cuatro palabras'],
        alarmSigns: ['No dice frases de dos palabras'],
      ),
      AreaMilestones(
        area: DevelopmentArea.socialEmotional,
        label: 'Social/afectivo',
        newMilestones: ['Respeta turnos en juegos sencillos', 'Comienza juegos de imitación'],
        alarmSigns: ['No muestra interés por otros niños'],
      ),
      AreaMilestones(
        area: DevelopmentArea.cognitive,
        label: 'Cognitivo',
        newMilestones: ['Hace juegos de imaginación sencillos', 'Clasifica objetos por color o forma'],
        alarmSigns: ['No imita ni hace juegos sencillos'],
      ),
    ],
    medicalDisclaimer: medicalDisclaimer,
  ),
  MonthContent(
    month: MilestoneMonth.month25,
    label: '24 a 25 meses',
    areas: [
      AreaMilestones(
        area: DevelopmentArea.grossMotor,
        label: 'Motricidad gruesa',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.fineMotor,
        label: 'Motricidad fina',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.language,
        label: 'Lenguaje',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.socialEmotional,
        label: 'Social/afectivo',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.cognitive,
        label: 'Cognitivo',
        newMilestones: ['Comprende el concepto de "lleno" y "vacío"'],
        alarmSigns: [],
      ),
    ],
    medicalDisclaimer: medicalDisclaimer,
  ),
  MonthContent(
    month: MilestoneMonth.month26,
    label: '25 a 26 meses',
    areas: [
      AreaMilestones(
        area: DevelopmentArea.grossMotor,
        label: 'Motricidad gruesa',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.fineMotor,
        label: 'Motricidad fina',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.language,
        label: 'Lenguaje',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.socialEmotional,
        label: 'Social/afectivo',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.cognitive,
        label: 'Cognitivo',
        newMilestones: ['Armar puzzles de dos o tres piezas'],
        alarmSigns: [],
      ),
    ],
    medicalDisclaimer: medicalDisclaimer,
  ),
  MonthContent(
    month: MilestoneMonth.month27,
    label: '26 a 27 meses',
    areas: [
      AreaMilestones(
        area: DevelopmentArea.grossMotor,
        label: 'Motricidad gruesa',
        newMilestones: ['Salta hacia delante'],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.fineMotor,
        label: 'Motricidad fina',
        newMilestones: ['Ensarta piezas grandes'],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.language,
        label: 'Lenguaje',
        newMilestones: ['Usa pronombres y preposiciones sencillas', 'Hace preguntas con "qué" y "dónde"'],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.socialEmotional,
        label: 'Social/afectivo',
        newMilestones: ['Participa en juegos de rol sencillos', 'Muestra independencia'],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.cognitive,
        label: 'Cognitivo',
        newMilestones: ['Completa puzzles sencillos', 'Comprende el concepto de "más"'],
        alarmSigns: [],
      ),
    ],
    medicalDisclaimer: medicalDisclaimer,
  ),
  MonthContent(
    month: MilestoneMonth.month28,
    label: '27 a 28 meses',
    areas: [
      AreaMilestones(
        area: DevelopmentArea.grossMotor,
        label: 'Motricidad gruesa',
        newMilestones: ['Empieza a correr con más firmeza'],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.fineMotor,
        label: 'Motricidad fina',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.language,
        label: 'Lenguaje',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.socialEmotional,
        label: 'Social/afectivo',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.cognitive,
        label: 'Cognitivo',
        newMilestones: ['Comprende el "porque" en situaciones sencillas'],
        alarmSigns: [],
      ),
    ],
    medicalDisclaimer: medicalDisclaimer,
  ),
  MonthContent(
    month: MilestoneMonth.month29,
    label: '28 a 29 meses',
    areas: [
      AreaMilestones(
        area: DevelopmentArea.grossMotor,
        label: 'Motricidad gruesa',
        newMilestones: ['Salta hacia delante con los dos pies'],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.fineMotor,
        label: 'Motricidad fina',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.language,
        label: 'Lenguaje',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.socialEmotional,
        label: 'Social/afectivo',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.cognitive,
        label: 'Cognitivo',
        newMilestones: ['Empareja objetos iguales por forma'],
        alarmSigns: [],
      ),
    ],
    medicalDisclaimer: medicalDisclaimer,
  ),
  MonthContent(
    month: MilestoneMonth.month30,
    label: '29 a 30 meses',
    areas: [
      AreaMilestones(
        area: DevelopmentArea.grossMotor,
        label: 'Motricidad gruesa',
        newMilestones: ['Se mantiene en un pie un instante', 'Patea una pelota'],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.fineMotor,
        label: 'Motricidad fina',
        newMilestones: ['Copia una línea vertical', 'Abrocha y desabrocha botones grandes'],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.language,
        label: 'Lenguaje',
        newMilestones: ['Dice frases de tres o más palabras', 'Conoce y nombra muchos objetos'],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.socialEmotional,
        label: 'Social/afectivo',
        newMilestones: ['Comparte juguetes a veces', 'Sigue rutinas sencillas'],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.cognitive,
        label: 'Cognitivo',
        newMilestones: ['Cuenta objetos hasta dos', 'Imita acciones de adultos'],
        alarmSigns: [],
      ),
    ],
    medicalDisclaimer: medicalDisclaimer,
  ),
  MonthContent(
    month: MilestoneMonth.month31,
    label: '30 a 31 meses',
    areas: [
      AreaMilestones(
        area: DevelopmentArea.grossMotor,
        label: 'Motricidad gruesa',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.fineMotor,
        label: 'Motricidad fina',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.language,
        label: 'Lenguaje',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.socialEmotional,
        label: 'Social/afectivo',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.cognitive,
        label: 'Cognitivo',
        newMilestones: ['Comprende el orden de las rutinas diarias'],
        alarmSigns: [],
      ),
    ],
    medicalDisclaimer: medicalDisclaimer,
  ),
  MonthContent(
    month: MilestoneMonth.month32,
    label: '31 a 32 meses',
    areas: [
      AreaMilestones(
        area: DevelopmentArea.grossMotor,
        label: 'Motricidad gruesa',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.fineMotor,
        label: 'Motricidad fina',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.language,
        label: 'Lenguaje',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.socialEmotional,
        label: 'Social/afectivo',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.cognitive,
        label: 'Cognitivo',
        newMilestones: ['Clasifica objetos por su función'],
        alarmSigns: [],
      ),
    ],
    medicalDisclaimer: medicalDisclaimer,
  ),
  MonthContent(
    month: MilestoneMonth.month33,
    label: '32 a 33 meses',
    areas: [
      AreaMilestones(
        area: DevelopmentArea.grossMotor,
        label: 'Motricidad gruesa',
        newMilestones: ['Camina de puntillas'],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.fineMotor,
        label: 'Motricidad fina',
        newMilestones: ['Usa las tijeras para recortar', 'Copia un círculo'],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.language,
        label: 'Lenguaje',
        newMilestones: ['Usa el plural y algunos tiempos verbales', 'Cuenta hasta tres'],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.socialEmotional,
        label: 'Social/afectivo',
        newMilestones: ['Juega a juegos de imaginación', 'Defiende su turno'],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.cognitive,
        label: 'Cognitivo',
        newMilestones: ['Comprende el juego de roles', 'Agrupa por tamaño'],
        alarmSigns: [],
      ),
    ],
    medicalDisclaimer: medicalDisclaimer,
  ),
  MonthContent(
    month: MilestoneMonth.month34,
    label: '33 a 34 meses',
    areas: [
      AreaMilestones(
        area: DevelopmentArea.grossMotor,
        label: 'Motricidad gruesa',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.fineMotor,
        label: 'Motricidad fina',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.language,
        label: 'Lenguaje',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.socialEmotional,
        label: 'Social/afectivo',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.cognitive,
        label: 'Cognitivo',
        newMilestones: ['Empieza a entender el concepto de "dentro" y "fuera"'],
        alarmSigns: [],
      ),
    ],
    medicalDisclaimer: medicalDisclaimer,
  ),
  MonthContent(
    month: MilestoneMonth.month35,
    label: '34 a 35 meses',
    areas: [
      AreaMilestones(
        area: DevelopmentArea.grossMotor,
        label: 'Motricidad gruesa',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.fineMotor,
        label: 'Motricidad fina',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.language,
        label: 'Lenguaje',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.socialEmotional,
        label: 'Social/afectivo',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.cognitive,
        label: 'Cognitivo',
        newMilestones: ['Completa puzzles de más piezas'],
        alarmSigns: [],
      ),
    ],
    medicalDisclaimer: medicalDisclaimer,
  ),
  MonthContent(
    month: MilestoneMonth.month36,
    label: '35 a 36 meses',
    areas: [
      AreaMilestones(
        area: DevelopmentArea.grossMotor,
        label: 'Motricidad gruesa',
        newMilestones: ['Sube escaleras alternando los pies', 'Salta en un pie'],
        alarmSigns: ['A menudo se cae o no puede saltar'],
      ),
      AreaMilestones(
        area: DevelopmentArea.fineMotor,
        label: 'Motricidad fina',
        newMilestones: ['Dibuja una persona con cabeza y algunas partes', 'Copia un cuadrado'],
        alarmSigns: ['Dificultad marcada para dibujar o manipular'],
      ),
      AreaMilestones(
        area: DevelopmentArea.language,
        label: 'Lenguaje',
        newMilestones: ['Mantiene una conversación sencilla', 'Cuenta hasta cinco', 'Dice su nombre y edad'],
        alarmSigns: ['Habla muy poco o poco comprensible'],
      ),
      AreaMilestones(
        area: DevelopmentArea.socialEmotional,
        label: 'Social/afectivo',
        newMilestones: ['Juega con otros niños en grupo', 'Comprende y respeta normas sencillas'],
        alarmSigns: ['No establece contacto visual ni juega con otros'],
      ),
      AreaMilestones(
        area: DevelopmentArea.cognitive,
        label: 'Cognitivo',
        newMilestones: ['Comprende secuencias sencillas', 'Empieza a entender operaciones básicas'],
        alarmSigns: ['No comprende instrucciones sencillas'],
      ),
    ],
    medicalDisclaimer: medicalDisclaimer,
  ),
  MonthContent(
    month: MilestoneMonth.month37,
    label: '36 a 37 meses',
    areas: [
      AreaMilestones(
        area: DevelopmentArea.grossMotor,
        label: 'Motricidad gruesa',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.fineMotor,
        label: 'Motricidad fina',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.language,
        label: 'Lenguaje',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.socialEmotional,
        label: 'Social/afectivo',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.cognitive,
        label: 'Cognitivo',
        newMilestones: ['Agrupa objetos por dos criterios'],
        alarmSigns: [],
      ),
    ],
    medicalDisclaimer: medicalDisclaimer,
  ),
  MonthContent(
    month: MilestoneMonth.month38,
    label: '37 a 38 meses',
    areas: [
      AreaMilestones(
        area: DevelopmentArea.grossMotor,
        label: 'Motricidad gruesa',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.fineMotor,
        label: 'Motricidad fina',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.language,
        label: 'Lenguaje',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.socialEmotional,
        label: 'Social/afectivo',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.cognitive,
        label: 'Cognitivo',
        newMilestones: ['Comprende cuentos y anticipa qué vendrá'],
        alarmSigns: [],
      ),
    ],
    medicalDisclaimer: medicalDisclaimer,
  ),
  MonthContent(
    month: MilestoneMonth.month39,
    label: '38 a 39 meses',
    areas: [
      AreaMilestones(
        area: DevelopmentArea.grossMotor,
        label: 'Motricidad gruesa',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.fineMotor,
        label: 'Motricidad fina',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.language,
        label: 'Lenguaje',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.socialEmotional,
        label: 'Social/afectivo',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.cognitive,
        label: 'Cognitivo',
        newMilestones: ['Resuelve puzzles sencillos por sí solo'],
        alarmSigns: [],
      ),
    ],
    medicalDisclaimer: medicalDisclaimer,
  ),
  MonthContent(
    month: MilestoneMonth.month40,
    label: '39 a 40 meses',
    areas: [
      AreaMilestones(
        area: DevelopmentArea.grossMotor,
        label: 'Motricidad gruesa',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.fineMotor,
        label: 'Motricidad fina',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.language,
        label: 'Lenguaje',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.socialEmotional,
        label: 'Social/afectivo',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.cognitive,
        label: 'Cognitivo',
        newMilestones: ['Entiende conceptos de cantidad: muchos y pocos'],
        alarmSigns: [],
      ),
    ],
    medicalDisclaimer: medicalDisclaimer,
  ),
  MonthContent(
    month: MilestoneMonth.month41,
    label: '40 a 41 meses',
    areas: [
      AreaMilestones(
        area: DevelopmentArea.grossMotor,
        label: 'Motricidad gruesa',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.fineMotor,
        label: 'Motricidad fina',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.language,
        label: 'Lenguaje',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.socialEmotional,
        label: 'Social/afectivo',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.cognitive,
        label: 'Cognitivo',
        newMilestones: ['Comprende el paso del tiempo: antes y después'],
        alarmSigns: [],
      ),
    ],
    medicalDisclaimer: medicalDisclaimer,
  ),
  MonthContent(
    month: MilestoneMonth.month42,
    label: '41 a 42 meses',
    areas: [
      AreaMilestones(
        area: DevelopmentArea.grossMotor,
        label: 'Motricidad gruesa',
        newMilestones: ['Camina en una línea'],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.fineMotor,
        label: 'Motricidad fina',
        newMilestones: ['Recorta con las tijeras siguiendo una línea', 'Copia un círculo'],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.language,
        label: 'Lenguaje',
        newMilestones: ['Cuenta hasta diez', 'Narra experiencias breves'],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.socialEmotional,
        label: 'Social/afectivo',
        newMilestones: ['Muestra empatía ante las emociones ajenas', 'Distingue lo suyo de lo ajeno'],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.cognitive,
        label: 'Cognitivo',
        newMilestones: ['Comprende conceptos de cantidad', 'Distingue el día de la noche'],
        alarmSigns: [],
      ),
    ],
    medicalDisclaimer: medicalDisclaimer,
  ),
  MonthContent(
    month: MilestoneMonth.month43,
    label: '42 a 43 meses',
    areas: [
      AreaMilestones(
        area: DevelopmentArea.grossMotor,
        label: 'Motricidad gruesa',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.fineMotor,
        label: 'Motricidad fina',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.language,
        label: 'Lenguaje',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.socialEmotional,
        label: 'Social/afectivo',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.cognitive,
        label: 'Cognitivo',
        newMilestones: ['Clasifica por forma, color y tamaño a la vez'],
        alarmSigns: [],
      ),
    ],
    medicalDisclaimer: medicalDisclaimer,
  ),
  MonthContent(
    month: MilestoneMonth.month44,
    label: '43 a 44 meses',
    areas: [
      AreaMilestones(
        area: DevelopmentArea.grossMotor,
        label: 'Motricidad gruesa',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.fineMotor,
        label: 'Motricidad fina',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.language,
        label: 'Lenguaje',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.socialEmotional,
        label: 'Social/afectivo',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.cognitive,
        label: 'Cognitivo',
        newMilestones: ['Entiende y explica secuencias simples de historias'],
        alarmSigns: [],
      ),
    ],
    medicalDisclaimer: medicalDisclaimer,
  ),
  MonthContent(
    month: MilestoneMonth.month45,
    label: '44 a 45 meses',
    areas: [
      AreaMilestones(
        area: DevelopmentArea.grossMotor,
        label: 'Motricidad gruesa',
        newMilestones: ['Corre con más control y para sin caerse'],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.fineMotor,
        label: 'Motricidad fina',
        newMilestones: ['Dibuja figuras reconocibles', 'Atrapa una pelota con las manos'],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.language,
        label: 'Lenguaje',
        newMilestones: ['Hace preguntas con "por qué"', 'Usa frases de cuatro a cinco palabras'],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.socialEmotional,
        label: 'Social/afectivo',
        newMilestones: ['Juega a juegos cooperativos', 'Expresa su opinión'],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.cognitive,
        label: 'Cognitivo',
        newMilestones: [],
        alarmSigns: [],
      ),
    ],
    medicalDisclaimer: medicalDisclaimer,
  ),
  MonthContent(
    month: MilestoneMonth.month46,
    label: '45 a 46 meses',
    areas: [
      AreaMilestones(
        area: DevelopmentArea.grossMotor,
        label: 'Motricidad gruesa',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.fineMotor,
        label: 'Motricidad fina',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.language,
        label: 'Lenguaje',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.socialEmotional,
        label: 'Social/afectivo',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.cognitive,
        label: 'Cognitivo',
        newMilestones: ['Comprende el "si entonces" básico'],
        alarmSigns: [],
      ),
    ],
    medicalDisclaimer: medicalDisclaimer,
  ),
  MonthContent(
    month: MilestoneMonth.month47,
    label: '46 a 47 meses',
    areas: [
      AreaMilestones(
        area: DevelopmentArea.grossMotor,
        label: 'Motricidad gruesa',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.fineMotor,
        label: 'Motricidad fina',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.language,
        label: 'Lenguaje',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.socialEmotional,
        label: 'Social/afectivo',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.cognitive,
        label: 'Cognitivo',
        newMilestones: ['Completa puzzles de 8 piezas o más'],
        alarmSigns: [],
      ),
    ],
    medicalDisclaimer: medicalDisclaimer,
  ),
  MonthContent(
    month: MilestoneMonth.month48,
    label: '47 a 48 meses',
    areas: [
      AreaMilestones(
        area: DevelopmentArea.grossMotor,
        label: 'Motricidad gruesa',
        newMilestones: ['Salta en un pie varias veces', 'Sabe andar en triciclo'],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.fineMotor,
        label: 'Motricidad fina',
        newMilestones: ['Copia una cruz', 'Usa los cubiertos con soltura'],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.language,
        label: 'Lenguaje',
        newMilestones: ['Cuenta historias sencillas', 'Sigue instrucciones de dos a tres pasos'],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.socialEmotional,
        label: 'Social/afectivo',
        newMilestones: ['Establece amistades', 'Participa en juegos con reglas'],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.cognitive,
        label: 'Cognitivo',
        newMilestones: [],
        alarmSigns: [],
      ),
    ],
    medicalDisclaimer: medicalDisclaimer,
  ),
  MonthContent(
    month: MilestoneMonth.month49,
    label: '48 a 49 meses',
    areas: [
      AreaMilestones(
        area: DevelopmentArea.grossMotor,
        label: 'Motricidad gruesa',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.fineMotor,
        label: 'Motricidad fina',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.language,
        label: 'Lenguaje',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.socialEmotional,
        label: 'Social/afectivo',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.cognitive,
        label: 'Cognitivo',
        newMilestones: ['Comprende conceptos espaciales: arriba, abajo, delante, detrás'],
        alarmSigns: [],
      ),
    ],
    medicalDisclaimer: medicalDisclaimer,
  ),
  MonthContent(
    month: MilestoneMonth.month50,
    label: '49 a 50 meses',
    areas: [
      AreaMilestones(
        area: DevelopmentArea.grossMotor,
        label: 'Motricidad gruesa',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.fineMotor,
        label: 'Motricidad fina',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.language,
        label: 'Lenguaje',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.socialEmotional,
        label: 'Social/afectivo',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.cognitive,
        label: 'Cognitivo',
        newMilestones: ['Distingue pesos: pesado y ligero'],
        alarmSigns: [],
      ),
    ],
    medicalDisclaimer: medicalDisclaimer,
  ),
  MonthContent(
    month: MilestoneMonth.month51,
    label: '50 a 51 meses',
    areas: [
      AreaMilestones(
        area: DevelopmentArea.grossMotor,
        label: 'Motricidad gruesa',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.fineMotor,
        label: 'Motricidad fina',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.language,
        label: 'Lenguaje',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.socialEmotional,
        label: 'Social/afectivo',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.cognitive,
        label: 'Cognitivo',
        newMilestones: ['Resuelve juegos de emparejar por lógica'],
        alarmSigns: [],
      ),
    ],
    medicalDisclaimer: medicalDisclaimer,
  ),
  MonthContent(
    month: MilestoneMonth.month52,
    label: '51 a 52 meses',
    areas: [
      AreaMilestones(
        area: DevelopmentArea.grossMotor,
        label: 'Motricidad gruesa',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.fineMotor,
        label: 'Motricidad fina',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.language,
        label: 'Lenguaje',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.socialEmotional,
        label: 'Social/afectivo',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.cognitive,
        label: 'Cognitivo',
        newMilestones: ['Comprende y sigue juegos con reglas sencillas'],
        alarmSigns: [],
      ),
    ],
    medicalDisclaimer: medicalDisclaimer,
  ),
  MonthContent(
    month: MilestoneMonth.month53,
    label: '52 a 53 meses',
    areas: [
      AreaMilestones(
        area: DevelopmentArea.grossMotor,
        label: 'Motricidad gruesa',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.fineMotor,
        label: 'Motricidad fina',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.language,
        label: 'Lenguaje',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.socialEmotional,
        label: 'Social/afectivo',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.cognitive,
        label: 'Cognitivo',
        newMilestones: ['Hace clasificaciones naturales y funcionales'],
        alarmSigns: [],
      ),
    ],
    medicalDisclaimer: medicalDisclaimer,
  ),
  MonthContent(
    month: MilestoneMonth.month54,
    label: '53 a 54 meses',
    areas: [
      AreaMilestones(
        area: DevelopmentArea.grossMotor,
        label: 'Motricidad gruesa',
        newMilestones: ['Camina hacia atrás con soltura'],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.fineMotor,
        label: 'Motricidad fina',
        newMilestones: ['Dibuja personas con más detalles'],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.language,
        label: 'Lenguaje',
        newMilestones: ['Describe imágenes y situaciones', 'Usa oraciones más complejas'],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.socialEmotional,
        label: 'Social/afectivo',
        newMilestones: ['Respeta mejor las normas sociales', 'Espera su turno con más paciencia'],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.cognitive,
        label: 'Cognitivo',
        newMilestones: [],
        alarmSigns: [],
      ),
    ],
    medicalDisclaimer: medicalDisclaimer,
  ),
  MonthContent(
    month: MilestoneMonth.month55,
    label: '54 a 55 meses',
    areas: [
      AreaMilestones(
        area: DevelopmentArea.grossMotor,
        label: 'Motricidad gruesa',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.fineMotor,
        label: 'Motricidad fina',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.language,
        label: 'Lenguaje',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.socialEmotional,
        label: 'Social/afectivo',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.cognitive,
        label: 'Cognitivo',
        newMilestones: ['Entiende el concepto de mitad'],
        alarmSigns: [],
      ),
    ],
    medicalDisclaimer: medicalDisclaimer,
  ),
  MonthContent(
    month: MilestoneMonth.month56,
    label: '55 a 56 meses',
    areas: [
      AreaMilestones(
        area: DevelopmentArea.grossMotor,
        label: 'Motricidad gruesa',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.fineMotor,
        label: 'Motricidad fina',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.language,
        label: 'Lenguaje',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.socialEmotional,
        label: 'Social/afectivo',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.cognitive,
        label: 'Cognitivo',
        newMilestones: ['Explica el orden de rutinas y secuencias'],
        alarmSigns: [],
      ),
    ],
    medicalDisclaimer: medicalDisclaimer,
  ),
  MonthContent(
    month: MilestoneMonth.month57,
    label: '56 a 57 meses',
    areas: [
      AreaMilestones(
        area: DevelopmentArea.grossMotor,
        label: 'Motricidad gruesa',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.fineMotor,
        label: 'Motricidad fina',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.language,
        label: 'Lenguaje',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.socialEmotional,
        label: 'Social/afectivo',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.cognitive,
        label: 'Cognitivo',
        newMilestones: ['Resuelve problemas contando con los dedos'],
        alarmSigns: [],
      ),
    ],
    medicalDisclaimer: medicalDisclaimer,
  ),
  MonthContent(
    month: MilestoneMonth.month58,
    label: '57 a 58 meses',
    areas: [
      AreaMilestones(
        area: DevelopmentArea.grossMotor,
        label: 'Motricidad gruesa',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.fineMotor,
        label: 'Motricidad fina',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.language,
        label: 'Lenguaje',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.socialEmotional,
        label: 'Social/afectivo',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.cognitive,
        label: 'Cognitivo',
        newMilestones: ['Comprende cuentos con secuencia temporal'],
        alarmSigns: [],
      ),
    ],
    medicalDisclaimer: medicalDisclaimer,
  ),
  MonthContent(
    month: MilestoneMonth.month59,
    label: '58 a 59 meses',
    areas: [
      AreaMilestones(
        area: DevelopmentArea.grossMotor,
        label: 'Motricidad gruesa',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.fineMotor,
        label: 'Motricidad fina',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.language,
        label: 'Lenguaje',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.socialEmotional,
        label: 'Social/afectivo',
        newMilestones: [],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.cognitive,
        label: 'Cognitivo',
        newMilestones: ['Anticipa consecuencias de acciones'],
        alarmSigns: [],
      ),
    ],
    medicalDisclaimer: medicalDisclaimer,
  ),
  MonthContent(
    month: MilestoneMonth.month60,
    label: '59 a 60 meses',
    areas: [
      AreaMilestones(
        area: DevelopmentArea.grossMotor,
        label: 'Motricidad gruesa',
        newMilestones: ['Salta con los dos pies a la vez en altura'],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.fineMotor,
        label: 'Motricidad fina',
        newMilestones: ['Copia triángulos y letras, recorta y pega con precisión'],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.language,
        label: 'Lenguaje',
        newMilestones: ['Cuenta hasta veinte', 'Conversa con frases completas y claras'],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.socialEmotional,
        label: 'Social/afectivo',
        newMilestones: ['Cuida su turno y coopera en grupo', 'Expresa emociones con palabras'],
        alarmSigns: [],
      ),
      AreaMilestones(
        area: DevelopmentArea.cognitive,
        label: 'Cognitivo',
        newMilestones: ['Distingue derecha e izquierda', 'Resuelve problemas y planifica'],
        alarmSigns: [],
      ),
    ],
    medicalDisclaimer: medicalDisclaimer,
  ),
];

MonthContent? contentFor(MilestoneMonth? month) {
  if (month == null) return null;
  for (final content in _allContent) {
    if (content.month == month) return content;
  }
  return null;
}
